name: Images
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
jobs:
  images:
    uses: fredrir/infra/.github/workflows/project-images.yml@ci-v1
