name: Build images
'on':
  push:
    branches:
    - main
permissions:
  contents: read
jobs:
  api:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: fredrir/infra/.github/workflows/build-image.yml@eb764b837d1fd10cb71fde1963500854aaef5d6c
    with:
      image: ghcr.io/fredrir/portfolio-api
      context: .
      dockerfile: apps/api/Dockerfile
      timeout-minutes: 150
      test-command: 'export BUILDKITD_FLAGS="$BUILDKITD_FLAGS --oci-worker-net=host"

        buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=ci --opt filename=Containerfile
        --opt platform=linux/amd64 --opt target=rust-tests

        buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=ci --opt filename=Containerfile
        --opt platform=linux/amd64 --opt target=quality-tests --opt build-arg:CI_REVISION="$GITHUB_SHA-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT"'
      build-args: APP_VERSION=${{ github.sha }}
  web:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: fredrir/infra/.github/workflows/build-image.yml@eb764b837d1fd10cb71fde1963500854aaef5d6c
    with:
      image: ghcr.io/fredrir/portfolio-web
      context: .
      dockerfile: apps/web/Dockerfile
      timeout-minutes: 150
      test-command: 'export BUILDKITD_FLAGS="$BUILDKITD_FLAGS --oci-worker-net=host"

        buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=ci --opt filename=Containerfile
        --opt platform=linux/amd64 --opt target=web-tests'
      build-args: 'VITE_RECAPTCHA_SITE_KEY=${{ vars.VITE_RECAPTCHA_SITE_KEY }}

        VITE_POSTHOG_KEY=${{ vars.VITE_POSTHOG_KEY }}

        VITE_POSTHOG_HOST=${{ vars.VITE_POSTHOG_HOST }}

        VITE_APP_VERSION=${{ github.sha }}'
  worker:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: fredrir/infra/.github/workflows/build-image.yml@eb764b837d1fd10cb71fde1963500854aaef5d6c
    with:
      image: ghcr.io/fredrir/portfolio-worker
      context: .
      dockerfile: apps/worker/Dockerfile
      timeout-minutes: 150
      test-command: 'export BUILDKITD_FLAGS="$BUILDKITD_FLAGS --oci-worker-net=host"

        buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=ci --opt filename=Containerfile
        --opt platform=linux/amd64 --opt target=rust-tests

        buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=ci --opt filename=Containerfile
        --opt platform=linux/amd64 --opt target=quality-tests --opt build-arg:CI_REVISION="$GITHUB_SHA-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT"'
      build-args: APP_VERSION=${{ github.sha }}
